---
version: 2

sphinx:
  configuration: doc/source/conf.py

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  apt_packages:
    - plantuml
    - libdbus-1-dev
    - libgirepository-2.0-dev
    - libcairo2-dev

python:
  install:
    - requirements: requirements-doc.txt
    - method: pip
      path: .
      extra_requirements:
        - all
